Class = require 'class'
require 'paddle'
require 'simpleScale'
require 'TSerial'
require 'eball'
require 'fullScreener'
require 'superPowerControl'
require 'mainMenu'
require 'music'
require 'animator'
require 'src/baseGame'
require 'src/constantvars'
require 'src/menus'
require 'src/reverseGame'
serialize = require 'ser'